apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-frontend
  labels:
    app: rag-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-frontend
  template:
    metadata:
      labels:
        app: rag-frontend
    spec:
      containers:
        - name: rag-frontend
          image: rag-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: rag-frontend
spec:
  selector:
    app: rag-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: ClusterIP
